spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:mora_plan}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Vibers@2112}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPoolPlans

server.port=8093
spring.application.name=plan-service
spring.cloud.consul.discovery.tags=traefik.enable=true,traefik.http.routers.plan.rule=PathPrefix(`/api/plans`)

spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:localhost}
spring.cloud.consul.port=${SPRING_CLOUD_CONSUL_PORT:8500}

spring.cloud.compatibility-verifier.enabled=false

spring.cloud.consul.discovery.prefer-ip-address=false
spring.cloud.consul.discovery.hostname=plan-service

management.endpoints.web.exposure.include=health
