export const PERFIS = {
  CONTRACTING_PROPERTY_MANAGER: 'CONTRACTING_PROPERTY_MANAGER',
  CONTRACTING_SYNDIC: 'CONTRACTING_SYNDIC',
  OPERATIONAL_SYNDIC: 'OPERATIONAL_SYNDIC',
  ADMINISTRATOR: 'ADMINISTRATOR',
  DOORMAN: 'DOORMAN',
  REAL_ESTATE_AGENCY: 'REAL_ESTATE_AGENCY',
  RESIDENT_OWNER: 'RESIDENT_OWNER',
  ABSENT_OWNER: 'ABSENT_OWNER',
  LESSEE: 'LESSEE',
  OCCUPANT: 'OCCUPANT',
  GUEST: 'GUEST',
};

export const PERFIS_CONDOMINIO = [
  PERFIS.OPERATIONAL_SYNDIC,
  PERFIS.ADMINISTRATOR,
  PERFIS.DOORMAN,
  PERFIS.REAL_ESTATE_AGENCY,
  PERFIS.RESIDENT_OWNER,
];

export const PERFIS_UNIDADE = [
  PERFIS.LESSEE,
  PERFIS.OCCUPANT,
  PERFIS.GUEST,
];

export const PERFIS_CADASTRO_CONDOMINIO = [
  PERFIS.OPERATIONAL_SYNDIC,
  PERFIS.ADMINISTRATOR,
  PERFIS.DOORMAN,
  PERFIS.REAL_ESTATE_AGENCY,
  PERFIS.RESIDENT_OWNER,
];

/** Perfis que podem cadastrar usuários de nível condomínio */
export const ATORES_CADASTRO_CONDOMINIO = [
  PERFIS.CONTRACTING_PROPERTY_MANAGER,
  PERFIS.CONTRACTING_SYNDIC,
];

/** Matriz: perfil do ator → perfis que pode cadastrar */
export const PERMISSOES_CADASTRO = {
  [PERFIS.CONTRACTING_PROPERTY_MANAGER]: PERFIS_CADASTRO_CONDOMINIO,
  [PERFIS.CONTRACTING_SYNDIC]: PERFIS_CADASTRO_CONDOMINIO,
  [PERFIS.ADMINISTRATOR]: PERFIS_CADASTRO_CONDOMINIO,
  [PERFIS.OPERATIONAL_SYNDIC]: PERFIS_CADASTRO_CONDOMINIO,
  [PERFIS.RESIDENT_OWNER]: [PERFIS.LESSEE, PERFIS.OCCUPANT, PERFIS.GUEST],
  [PERFIS.ABSENT_OWNER]: [PERFIS.LESSEE],
  [PERFIS.LESSEE]: [PERFIS.OCCUPANT, PERFIS.GUEST],
};

/** Perfis que exigem unidadeId no convite */
export const PERFIS_EXIGEM_UNIDADE = [
  PERFIS.RESIDENT_OWNER,
  PERFIS.ABSENT_OWNER,
  PERFIS.LESSEE,
  PERFIS.OCCUPANT,
  PERFIS.GUEST,
];

export const STATUS_USUARIO = {
  PENDING_ACTIVATION: 'pending_activation',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
};

export const STATUS_CONVITE = {
  PENDING: 'pending',
  USED: 'used',
  EXPIRED: 'expired',
  REVOKED: 'revoked',
};

export const CONDOMINIO_DEFAULT = 'default';

export function podeCadastrarPerfil(perfilAtor, perfilAlvo) {
  const permitidos = PERMISSOES_CADASTRO[perfilAtor];
  return permitidos?.includes(perfilAlvo) ?? false;
}

export function perfilExigeUnidade(perfil) {
  return PERFIS_EXIGEM_UNIDADE.includes(perfil);
}

export function perfilRequerPrecadastro(perfil) {
  return PERFIS_UNIDADE.includes(perfil);
}

export const PERFIS_ACESSO_ADMIN = [
  PERFIS.CONTRACTING_PROPERTY_MANAGER,
  PERFIS.CONTRACTING_SYNDIC,
  PERFIS.OPERATIONAL_SYNDIC,
  PERFIS.ADMINISTRATOR,
];

export const PERFIS_GESTAO_USUARIOS = [
  ...PERFIS_ACESSO_ADMIN,
  PERFIS.RESIDENT_OWNER,
  PERFIS.ABSENT_OWNER,
  PERFIS.LESSEE,
];

export function podeAcessarAdmin(perfil) {
  return PERFIS_ACESSO_ADMIN.includes(perfil);
}

export function podeGerenciarUsuarios(perfil) {
  return PERFIS_GESTAO_USUARIOS.includes(perfil);
}

export function podeGerenciarOcupantes(perfil) {
  return [
    PERFIS.RESIDENT_OWNER,
    PERFIS.ABSENT_OWNER,
    PERFIS.LESSEE,
  ].includes(perfil);
}

export const PERFIS_OCUPANTE_UNIDADE = [
  PERFIS.LESSEE,
  PERFIS.OCCUPANT,
  PERFIS.GUEST,
];

export function isPerfilCondominio(perfil) {
  return [
    PERFIS.CONTRACTING_PROPERTY_MANAGER,
    PERFIS.CONTRACTING_SYNDIC,
    PERFIS.OPERATIONAL_SYNDIC,
    PERFIS.ADMINISTRATOR,
    PERFIS.DOORMAN,
    PERFIS.REAL_ESTATE_AGENCY,
  ].includes(perfil);
}
