spring.application.name=meeting

spring.datasource.url=jdbc:mysql://localhost:3306/mora?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=A992176566kemi_@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL que o Spring está gerando no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Apague a linha anterior e tente esta:
#spring.jackson.serialization.write_dates_as_timestamps=false

#Configuração do Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#Configurações do Pool de Conexões (HikariCP)
# Número máximo de conexões abertas com o banco (ajuste conforme o porte da aplicação)
spring.datasource.hikari.maximum-pool-size=10
# Tempo mínimo que uma conexão pode ficar ociosa no pool antes de ser fechada
spring.datasource.hikari.idle-timeout=30000
# Tempo máximo que o Spring espera para conseguir uma conexão do pool antes de dar erro
spring.datasource.hikari.connection-timeout=20000
# Tempo máximo de vida de uma conexão no pool
spring.datasource.hikari.max-lifetime=1800000
# Nome do pool para facilitar a leitura nos logs de erro
spring.datasource.hikari.pool-name=HikariPoolMeetings

server.port = 8081
