spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:mora}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Vibers@2112}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL que o Spring esta gerando no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Desabilitar execucao automatica do schema.sql (Hibernate cria via ddl-auto)
spring.sql.init.mode=never

#Configuracao do Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#Configuracoes do Pool de Conexoes (HikariCP)
# Numero maximo de conexoes abertas com o banco (ajuste conforme o porte da aplicacao)
spring.datasource.hikari.maximum-pool-size=10
# Tempo minimo que uma conexao pode ficar ociosa no pool antes de ser fechada
spring.datasource.hikari.idle-timeout=30000
# Tempo maximo que o Spring espera para conseguir uma conexao do pool antes de dar erro
spring.datasource.hikari.connection-timeout=20000
# Tempo maximo de vida de uma conexao no pool
spring.datasource.hikari.max-lifetime=1800000
# Nome do pool para facilitar a leitura nos logs de erro
spring.datasource.hikari.pool-name=HikariPoolMeetings


server.port=8091
spring.application.name=meeting-service
spring.cloud.consul.discovery.tags=traefik.enable=true,traefik.http.routers.meeting.rule=PathPrefix(`/api/meetings`)

spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:localhost}
spring.cloud.consul.port=${SPRING_CLOUD_CONSUL_PORT:8500}

spring.cloud.compatibility-verifier.enabled=false

spring.cloud.consul.discovery.prefer-ip-address=false
spring.cloud.consul.discovery.hostname=meeting-service

management.endpoints.web.exposure.include=health
